language: c
dist: xenial
osx_image: xcode10.2

compiler:
- gcc
- clang

os:
- linux
- osx

env:
- BUILD_TYPE=RelWithDebInfo

addons:
  apt:
    sources:
    - llvm-toolchain-xenial-8
    - ubuntu-toolchain-r-test
    packages:
    - clang
    - cmake
    - gcc
    - ninja-build
    - libcunit1-dev
  homebrew:
    packages:
    - cmake
    - gcc@9
    - llvm@8
    - ninja
    - cunit
    - curl-openssl
    update: true

install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    export PATH="$(brew --prefix llvm)/bin:$PATH";
  fi
- echo ${CC}
- ${CC} --version
- cmake --version

before_script:
- mkdir -p build && cd build
- cmake .. -G Ninja -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTS=ON
- cmake --build .
- cd ..

script:
- cd build && ctest --verbose

