language: c
dist: xenial
osx_image: xcode10.2

compiler:
- gcc
- clang

os:
- linux
- osx

env:
- BUILD_TYPE=Debug
- BUILD_TYPE=RelWithDebInfo

addons:
  apt:
    sources:
    - llvm-toolchain-xenial-8
    - ubuntu-toolchain-r-test
    packages:
    - clang-8
    - cmake
    - gcc-9
    - ninja-build
    - libcunit1-dev
  homebrew:
    packages:
    - cmake
    - gcc@9
    - llvm@8
    - ninja
    - cunit
    update: true

install:
# The following Homebrew packages aren't linked by default, and need to be
# prepended to the path explicitly.
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    export PATH="$(brew --prefix llvm)/bin:$PATH";
  fi

# /usr/bin/gcc points to an older compiler on both Linux and macOS.
- if [ "$CC" = "gcc" ]; then export CC="gcc-9"; fi

# /usr/bin/clang points to an older compiler on both Linux and macOS.
#
# Homebrew's llvm package doesn't ship a versioned clang++ binary, so the values
# below don't work on macOS. Fortunately, the path change above makes the
# default values (clang and clang++) resolve to the correct compiler on macOS.
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    if [ "$CC" = "clang" ]; then export CC="clang-8"; fi;
  fi

- echo ${CC}
- ${CC} --version
- cmake --version

before_script:
- mkdir -p build && cd build
- cmake .. -G Ninja -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTS=ON
- cmake --build .
- cd ..

script:
- cd build && ctest --verbose && cd ..

